/* Fotos de los platos: todas son del Instagram oficial de UMAI (@umaisushihn).
 * Cada una apunta a la publicaci\u00f3n de donde sali\u00f3 ("fuente").
 * real:true  -> es la foto de ese plato.
 * real:false -> imagen ilustrativa: foto de UMAI de un plato parecido. La tarjeta
 *               muestra la etiqueta "Imagen ilustrativa"; al poner la foto correcta,
 *               cambiar a real:true (o reemplazar el archivo) y la etiqueta desaparece.
 * nota: advertencia para revisar con el restaurante (no se muestra en las tarjetas).
 */
UMAI.fotosOrigen = "Instagram @umaisushihn";
UMAI.fotos = {
    "a1": {"src": "fotos/a1.jpg", "fuente": "https://www.instagram.com/p/C7SULZAJdEY/", "real": true},
    "a2": {"src": "fotos/a2.jpg", "fuente": "https://www.instagram.com/p/CqyFfdELEHC/", "real": true},
    "a3": {"src": "fotos/a3.jpg", "fuente": "https://www.instagram.com/p/C2DNhStJ3GV/", "real": true},
    "b1": {"src": "fotos/b1.jpg", "fuente": "https://www.instagram.com/p/C-vd9wSJu3z/", "real": true, "nota": "Bento real de UMAI; la publicaci\u00f3n no dice cu\u00e1l de los 4 es."},
    "b2": {"src": "fotos/b2.jpg", "fuente": "https://www.instagram.com/p/DA9SF8BpMdH/", "real": true, "nota": "Bento real de UMAI; la publicaci\u00f3n no dice cu\u00e1l de los 4 es."},
    "b3": {"src": "fotos/b3.jpg", "fuente": "https://www.instagram.com/reel/C_V-ce0p3ZN/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "b4": {"src": "fotos/b4.jpg", "fuente": "https://www.instagram.com/p/DACIUTfpplA/", "real": true, "nota": "Foto de los 4 bentos juntos."},
    "d1": {"src": "fotos/d1.jpg", "fuente": "https://www.instagram.com/p/C_n2OyYpJU_/", "real": true},
    "e1": {"src": "fotos/e1.jpg", "fuente": "https://www.instagram.com/p/CoV2ontpPkq/", "real": true},
    "e2": {"src": "fotos/e2.jpg", "fuente": "https://www.instagram.com/reel/CUbCtPugeWF/", "real": true, "nota": "Portada de un reel."},
    "e3": {"src": "fotos/e3.jpg", "fuente": "https://www.instagram.com/p/C6H5E33pV6s/", "real": true},
    "e4": {"src": "fotos/e4.jpg", "fuente": "https://www.instagram.com/p/CwLIjA9rC2l/", "real": true},
    "e5": {"src": "fotos/e5.jpg", "fuente": "https://www.instagram.com/p/CfaArf3umiq/", "real": true},
    "e6": {"src": "fotos/e6.jpg", "fuente": "https://www.instagram.com/p/CZAvei2u1ha/", "real": true},
    "e7": {"src": "fotos/e7.jpg", "fuente": "https://www.instagram.com/p/Cvfu0fEJoEX/", "real": true},
    "e8": {"src": "fotos/e8.jpg", "fuente": "https://www.instagram.com/reel/DLsf3QXJk8L/", "real": true, "nota": "Portada de un reel."},
    "g1": {"src": "fotos/g1.jpg", "fuente": "https://www.instagram.com/p/DE_A-jSJ-EV/", "real": true},
    "g2": {"src": "fotos/g2.jpg", "fuente": "https://www.instagram.com/p/CuF1nZUJj_c/", "real": true},
    "g3": {"src": "fotos/g3.jpg", "fuente": "https://www.instagram.com/p/DIji4CwphzM/", "real": true},
    "g4": {"src": "fotos/g4.jpg", "fuente": "https://www.instagram.com/p/DBEnCtaJam0/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "g5": {"src": "fotos/g5.jpg", "fuente": "https://www.instagram.com/p/C2ySJpupTfr/", "real": true},
    "g6": {"src": "fotos/g6.jpg", "fuente": "https://www.instagram.com/p/CZztOhKvzya/", "real": true, "nota": "La foto trae impreso \u00abNigiri de pulpo\u00bb."},
    "h1": {"src": "fotos/h1.jpg", "fuente": "https://www.instagram.com/p/Cgc-CzvOFQx/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "h2": {"src": "fotos/h2.jpg", "fuente": "https://www.instagram.com/p/Cau3s1VOBnm/", "real": true},
    "h3": {"src": "fotos/h3.jpg", "fuente": "https://www.instagram.com/p/CXMj4OqPXdE/", "real": true},
    "h4": {"src": "fotos/h4.jpg", "fuente": "https://www.instagram.com/p/CcypwxzuRyi/", "real": true},
    "i1": {"src": "fotos/i1.jpg", "fuente": "https://www.instagram.com/p/CWJYe8sPCd2/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "i2": {"src": "fotos/i2.jpg", "fuente": "https://www.instagram.com/p/C9iMuvQJ24H/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "i3": {"src": "fotos/i3.jpg", "fuente": "https://www.instagram.com/p/DGoleaYJ2Lr/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "k1": {"src": "fotos/k1.jpg", "fuente": "https://www.instagram.com/p/C1NwAQWJFUZ/", "real": true},
    "k2": {"src": "fotos/k2.jpg", "fuente": "https://www.instagram.com/p/DAE96kMJUXP/", "real": true},
    "k3": {"src": "fotos/k3.jpg", "fuente": "https://www.instagram.com/p/DJzcw5epNif/", "real": true},
    "m1": {"src": "fotos/m1.jpg", "fuente": "https://www.instagram.com/p/C5hK-xtJbHg/", "real": true},
    "m2": {"src": "fotos/m2.jpg", "fuente": "https://www.instagram.com/p/CWv24iGLIMm/", "real": true},
    "n1": {"src": "fotos/n1.jpg", "fuente": "https://www.instagram.com/p/DN_C9EuDT9R/", "real": true},
    "n2": {"src": "fotos/n2.jpg", "fuente": "https://www.instagram.com/p/CeRffxGuOqK/", "real": true},
    "n3": {"src": "fotos/n3.jpg", "fuente": "https://www.instagram.com/p/CSUnMNOrbVf/", "real": true},
    "n4": {"src": "fotos/n4.jpg", "fuente": "https://www.instagram.com/p/CduAwmiIVDv/", "real": true},
    "n5": {"src": "fotos/n5.jpg", "fuente": "https://www.instagram.com/p/DDKmO0aJtBv/", "real": true},
    "o1": {"src": "fotos/o1.jpg", "fuente": "https://www.instagram.com/p/CYCLX28uIkt/", "real": true},
    "o2": {"src": "fotos/o2.jpg", "fuente": "https://www.instagram.com/p/CXRWDueOhkj/", "real": true},
    "o3": {"src": "fotos/o3.jpg", "fuente": "https://www.instagram.com/p/CjlOQsZuTEa/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "p1": {"src": "fotos/p1.jpg", "fuente": "https://www.instagram.com/p/DNi0YHFgKQj/", "real": true},
    "p2": {"src": "fotos/p2.jpg", "fuente": "https://www.instagram.com/p/CYzK-YVOBkH/", "real": true},
    "p3": {"src": "fotos/p3.jpg", "fuente": "https://www.instagram.com/p/CmcoPevJEaH/", "real": true},
    "r1": {"src": "fotos/r1.jpg", "fuente": "https://www.instagram.com/p/DP7GyCUkuJk/", "real": true},
    "s1": {"src": "fotos/s1.jpg", "fuente": "https://www.instagram.com/p/DTjHh2RDbQh/", "real": true},
    "s2": {"src": "fotos/s2.jpg", "pos": "center 22%", "fuente": "https://www.instagram.com/reel/DXIZAYpiQkO/", "real": true, "nota": "Portada de un reel."},
    "s3": {"src": "fotos/s3.jpg", "fuente": "https://www.instagram.com/p/CzzLudupemO/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "s4": {"src": "fotos/s4.jpg", "fuente": "https://www.instagram.com/reel/DTQiX0CACAs/", "real": true, "nota": "Portada de un reel."},
    "s5": {"src": "fotos/s5.jpg", "fuente": "https://www.instagram.com/p/DIZSt9ZJBvq/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "s6": {"src": "fotos/s6.jpg", "fuente": "https://www.instagram.com/p/CQ6gX3LL9VY/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "s7": {"src": "fotos/s7.jpg", "fuente": "https://www.instagram.com/p/DYFoK1kFGlW/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "s8": {"src": "fotos/s8.jpg", "fuente": "https://www.instagram.com/p/DVbvMdBEVtM/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "s9": {"src": "fotos/s9.jpg", "fuente": "https://www.instagram.com/p/DUJKeFNgKBt/", "real": true},
    "t1": {"src": "fotos/t1.jpg", "fuente": "https://www.instagram.com/p/DK4-5anpuP_/", "real": true},
    "t2": {"src": "fotos/t2.jpg", "fuente": "https://www.instagram.com/p/C-nf1WZJWgB/", "real": true},
    "t3": {"src": "fotos/t3.jpg", "fuente": "https://www.instagram.com/p/C9sWanbJvxb/", "real": true},
    "u1": {"src": "fotos/u1.jpg", "fuente": "https://www.instagram.com/p/C3JSdP6pyzi/", "real": true},
    "u2": {"src": "fotos/u2.jpg", "fuente": "https://www.instagram.com/p/Ce4DR4bO5Hh/", "real": true},
    "u3": {"src": "fotos/u3.jpg", "fuente": "https://www.instagram.com/p/CVOqvvfIKBC/", "real": true},
    "u4": {"src": "fotos/u4.jpg", "fuente": "https://www.instagram.com/p/CfxhzOKOVOz/", "real": true},
    "u5": {"src": "fotos/u5.jpg", "fuente": "https://www.instagram.com/p/CqG98yApjrC/", "real": true},
    "u6": {"src": "fotos/u6.jpg", "fuente": "https://www.instagram.com/p/Cc_ByURuvPx/", "real": true},
    "u7": {"src": "fotos/u7.jpg", "fuente": "https://www.instagram.com/p/Cv0qEkrpuXv/", "real": true},
    "u8": {"src": "fotos/u8.jpg", "fuente": "https://www.instagram.com/p/CVwGmYXrnpv/", "real": true},
    "u9": {"src": "fotos/u9.jpg", "fuente": "https://www.instagram.com/p/CnNtVMIJNyT/", "real": true},
    "u10": {"src": "fotos/u10.jpg", "fuente": "https://www.instagram.com/p/CUIdX7JLhNc/", "real": true},
    "u11": {"src": "fotos/u11.jpg", "fuente": "https://www.instagram.com/p/C2snMLlJscn/", "real": true},
    "u12": {"src": "fotos/u12.jpg", "fuente": "https://www.instagram.com/p/C3TB5d4JSkw/", "real": true},
    "u13": {"src": "fotos/u13.jpg", "fuente": "https://www.instagram.com/p/C2dhfkCJ4ji/", "real": true},
    "u14": {"src": "fotos/u14.jpg", "fuente": "https://www.instagram.com/p/C5JZIg3JQi5/", "real": true},
    "u15": {"src": "fotos/u15.jpg", "fuente": "https://www.instagram.com/reel/Cbxv91zPOqs/", "real": true, "nota": "Portada de un reel."},
    "u16": {"src": "fotos/u16.jpg", "fuente": "https://www.instagram.com/p/CebmiL-O-K9/", "real": true},
    "u17": {"src": "fotos/u17.jpg", "fuente": "https://www.instagram.com/p/C2-fBM-J_Yz/", "real": true},
    "u18": {"src": "fotos/u18.jpg", "fuente": "https://www.instagram.com/p/CfUq04nOsBL/", "real": true},
    "u19": {"src": "fotos/u19.jpg", "fuente": "https://www.instagram.com/p/C4s45b5rXXF/", "real": true},
    "u20": {"src": "fotos/u20.jpg", "fuente": "https://www.instagram.com/p/CeMeRfgujcA/", "real": true},
    "u21": {"src": "fotos/u21.jpg", "fuente": "https://www.instagram.com/p/CVoOkVvvoqB/", "real": true},
    "u22": {"src": "fotos/u22.jpg", "fuente": "https://www.instagram.com/p/CetyeVYuvry/", "real": true},
    "u23": {"src": "fotos/u23.jpg", "fuente": "https://www.instagram.com/p/CpxyTLMp8yw/", "real": true},
    "u24": {"src": "fotos/u24.jpg", "fuente": "https://www.instagram.com/p/DHBoHAdJ_uu/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "u25": {"src": "fotos/u25.jpg", "fuente": "https://www.instagram.com/p/C950euiJK2X/", "real": true},
    "u26": {"src": "fotos/u26.jpg", "fuente": "https://www.instagram.com/reel/CU0SQEJg-dW/", "real": true, "nota": "Portada de un reel."},
    "u27": {"src": "fotos/u27.jpg", "fuente": "https://www.instagram.com/p/DDxYZTVJ0YX/", "real": true},
    "x1": {"src": "fotos/x1.jpg", "fuente": "https://www.instagram.com/p/CdWUrbuOo7R/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "x2": {"src": "fotos/x2.jpg", "fuente": "https://www.instagram.com/p/COgoRMLjI1J/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "x3": {"src": "fotos/x3.jpg", "fuente": "https://www.instagram.com/p/C54W7tJp6AT/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "x4": {"src": "fotos/x4.jpg", "fuente": "https://www.instagram.com/p/DHGu8FQJavh/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "x5": {"src": "fotos/x5.jpg", "fuente": "https://www.instagram.com/p/DEIS1YIp252/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "x6": {"src": "fotos/x6.jpg", "fuente": "https://www.instagram.com/p/CqQwKPrJywe/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "y1": {"src": "fotos/y1.jpg", "fuente": "https://www.instagram.com/p/C0-AaYaJkBH/", "real": true, "nota": "Yakitori real de UMAI; la prote\u00edna (pollo) no est\u00e1 confirmada en la publicaci\u00f3n."},
    "y2": {"src": "fotos/y2.jpg", "fuente": "https://www.instagram.com/p/DA7HVGNJ_es/", "real": true, "nota": "Yakitori real de UMAI; la prote\u00edna (res) no est\u00e1 confirmada en la publicaci\u00f3n."},
    "y3": {"src": "fotos/y3.jpg", "fuente": "https://www.instagram.com/p/CybYnp4J2bx/", "real": false, "nota": "Imagen ilustrativa: foto de UMAI de otro plato parecido; no es este producto."},
    "y4": {"src": "fotos/y4.jpg", "fuente": "https://www.instagram.com/p/DBhXCDCpRJN/", "real": true, "nota": "Yakitori real de UMAI; no se confirma si es el mixto."}
};
UMAI.items.forEach(function(i){
  var f = UMAI.fotos[i.id];
  if(f){ i.img = f.src; i.imgRef = !f.real; }
});
